# Generated by Django 5.1.7 on 2025-03-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'permissions': [('can_view_advertisement', 'Может просматривать рекламные компании'), ('can_add_advertisement', 'Может добавлять рекламные компании'), ('can_change_advertisement', 'Может изменять рекламные компании'), ('can_delete_advertisement', 'Может удалять рекламные компании')], 'verbose_name': 'Рекламная кампания', 'verbose_name_plural': 'Рекламные кампании'},
        ),
    ]
