# Generated by Django 5.1.7 on 2025-03-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="contracts",
            field=models.ManyToManyField(
                blank=True,
                related_name="advertisements_for_campaigns",
                to="contracts.contract",
            ),
        ),
    ]
