# Generated by Django 5.1.7 on 2025-03-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_advertisement_contracts"),
        ("contracts", "0002_alter_contract_advertisement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="contracts",
            field=models.ManyToManyField(
                blank=True, related_name="advertisements", to="contracts.contract"
            ),
        ),
    ]
