# Generated by Django 5.1.7 on 2025-03-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_advertisement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='channel',
            field=models.CharField(default=1, max_length=100, verbose_name='Канал продвижения'),
            preserve_default=False,
        ),
    ]
