# Generated by Django 5.1.7 on 2025-03-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_advertisement_contracts"),
        ("contracts", "0003_alter_contract_advertisement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="contracts",
            field=models.ManyToManyField(
                blank=True,
                related_name="advertisements_contracts",
                to="contracts.contract",
            ),
        ),
    ]
