# Generated by Django 5.1.7 on 2025-03-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_advertisement_contracts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="contracts",
        ),
    ]
