# Generated by Django 5.1.7 on 2025-03-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_view_product', 'Может просматривать продукт'), ('can_add_product', 'Может добавлять продукт'), ('can_change_product', 'Может изменять продукт'), ('can_delete_product', 'Может удалять продукт')], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
