# Generated by Django 5.1.7 on 2025-03-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'permissions': [('can_view_lead', 'Может просматривать лид'), ('can_add_lead', 'Может добавлять лид'), ('can_change_lead', 'Может изменять лид'), ('can_delete_lead', 'Может удалять лид')], 'verbose_name': 'Лид', 'verbose_name_plural': 'Лиды'},
        ),
    ]
