# Generated by Django 5.1.7 on 2025-03-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="ads.advertisement",
                        verbose_name="Рекламная кампания",
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leads.lead",
                        verbose_name="Лид",
                    ),
                ),
            ],
            options={
                "verbose_name": "Активный клиент",
                "verbose_name_plural": "Активные клиенты",
                "permissions": [
                    ("can_view_customer", "Может просматривать клиентов"),
                    ("can_add_customer", "Может добавлять клиентов"),
                    ("can_change_customer", "Может изменять клиентов"),
                    ("can_delete_customer", "Может удалять клиентов"),
                ],
            },
        ),
    ]
