# Generated by Django 5.1.7 on 2025-03-26 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("leads", "0002_alter_lead_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="advertisement",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="customer",
            name="lead",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.lead",
                verbose_name="Потенциальный клиент",
            ),
        ),
    ]
