# Generated by Django 5.1.7 on 2025-03-24 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_advertisement_options'),
        ('customers', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='advertisement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='ads.advertisement', verbose_name='Рекламная кампания'),
            preserve_default=False,
        ),
    ]
