# Generated by Django 5.1.7 on 2025-03-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0012_remove_contract_customer"),
        ("customers", "0003_customer_advertisement"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_contract",
                to="contracts.contract",
                verbose_name="Контракт",
            ),
        ),
    ]
