# Generated by Django 5.1.7 on 2025-03-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_customer_advertisement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="advertisement",
        ),
    ]
