# Generated by Django 5.1.7 on 2025-03-26 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_remove_advertisement_contracts"),
        ("customers", "0007_remove_customer_advertisement"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="advertisement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_set",
                to="ads.advertisement",
                verbose_name="Рекламная кампания",
            ),
        ),
    ]
