# Generated by Django 5.1.7 on 2025-03-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_customer_advertisement"),
        ("leads", "0002_alter_lead_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="advertisement",
        ),
        migrations.AlterField(
            model_name="customer",
            name="lead",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_leads",
                to="leads.lead",
                verbose_name="Потенциальный клиент",
            ),
        ),
    ]
