# Generated by Django 5.1.7 on 2025-03-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('can_view_customer', 'Может просматривать клиентов'), ('can_add_customer', 'Может добавлять клиентов'), ('can_change_customer', 'Может изменять клиентов'), ('can_delete_customer', 'Может удалять клиентов')], 'verbose_name': 'Активный клиент', 'verbose_name_plural': 'Активные клиенты'},
        ),
    ]
