# Generated by Django 5.1.7 on 2025-03-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_advertisement_options'),
        ('customers', '0003_customer_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='ads.advertisement', verbose_name='Рекламная кампания'),
        ),
    ]
