# Generated by Django 5.1.7 on 2025-03-26 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_advertisement_contracts"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="advertisement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts_for_advertisement",
                to="ads.advertisement",
                verbose_name="Рекламная кампания",
            ),
        ),
    ]
