# Generated by Django 5.1.7 on 2025-03-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'permissions': [('can_view_contract', 'Может просматривать контракты'), ('can_add_contract', 'Может добавлять контракты'), ('can_change_contract', 'Может изменять контракты'), ('can_delete_contract', 'Может удалять контракты')], 'verbose_name': 'Контракт', 'verbose_name_plural': 'Контракты'},
        ),
    ]
