# Generated by Django 5.1.7 on 2025-03-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_alter_contract_advertisement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="advertisement",
        ),
    ]
