# Generated by Django 5.1.7 on 2025-03-26 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_remove_advertisement_contracts"),
        ("contracts", "0006_contract_advertisement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="advertisement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts_advertisements",
                to="ads.advertisement",
                verbose_name="Рекламная кампания",
            ),
        ),
    ]
