# Generated by Django 5.1.7 on 2025-03-26 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0007_alter_contract_advertisement"),
        ("customers", "0002_remove_customer_advertisement_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="advertisement",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="price",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="start_date",
        ),
        migrations.AddField(
            model_name="contract",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Сумма контракта",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="conclusion_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата заключения"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="period",
            field=models.IntegerField(
                default=1, verbose_name="Период действия в месяцах"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="customers.customer",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="products.product",
                verbose_name="Услуга",
            ),
        ),
    ]
