# Generated by Django 5.1.7 on 2025-03-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0008_remove_contract_advertisement_and_more"),
        ("customers", "0002_remove_customer_advertisement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="customers.customer",
                verbose_name="Клиент",
            ),
        ),
    ]
