# Generated by Django 5.1.7 on 2025-03-26 16:23

import apps.contracts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0009_alter_contract_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="conclusion_date",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="period",
        ),
        migrations.AddField(
            model_name="contract",
            name="end_date",
            field=models.DateField(
                default=apps.contracts.models.one_month_from_today,
                verbose_name="Дата окончания",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата начала"
            ),
        ),
    ]
