# Generated by Django 5.1.7 on 2025-03-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0010_remove_contract_conclusion_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="amount",
            new_name="price",
        ),
    ]
