# Generated by Django 5.1.7 on 2025-03-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0011_rename_amount_contract_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="customer",
        ),
    ]
