# Generated by Django 5.1.7 on 2025-03-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={
                "permissions": [
                    ("can_view_lead", "Может просматривать потен-ых клиентов"),
                    ("can_add_lead", "Может добавлять потен-ых клиентов"),
                    ("can_change_lead", "Может изменять потен-ых клиентов"),
                    ("can_delete_lead", "Может удалять потен-ых клиентов"),
                ],
                "verbose_name": "Потенциальный клиент",
                "verbose_name_plural": "Потенциальные клиенты",
            },
        ),
    ]
